version: "3.8"
services:
  moodle:
    build:
      context: .
      dockerfile: moodle/Dockerfile
    volumes:
      - moodledata:/var/www/moodledata
      - ./plugins/events:/var/www/html/admin/tool/events
      - ./plugins/study:/var/www/html/mod/study
      - ./plugins/clever_oauth2/service/clever.php:/var/www/html/lib/classes/oauth2/service/clever.php
      - ./plugins/clever_oauth2/client/clever.php:/var/www/html/lib/classes/oauth2/client/clever.php
      - ./plugins/clever_oauth2/tool/issuers.php:/var/www/html/admin/tool/oauth2/issuers.php
      - ./plugins/clever_oauth2/tool/tool_oauth2.php:/var/www/html/admin/tool/oauth2/lang/en/tool_oauth2.php
    networks:
      - raisemoodle
    environment:
      MOODLE_DOCKER_DBHOST: postgres
      MOODLE_DOCKER_DBNAME: $POSTGRES_DB
      MOODLE_DOCKER_DBUSER: $POSTGRES_USER
      MOODLE_DOCKER_DBPASS: $POSTGRES_PASSWORD
      MOODLE_DOCKER_WWWROOT: http://localhost:8000
      MOODLE_DOCKER_DATAROOT: /var/www/moodledata
      EVENTSAPI_SERVER: eventsapi
    ports:
      - 8000:80
    depends_on:
      - postgres
  cron:
    build:
      context: .
      dockerfile: moodle/Dockerfile
    command: /bin/bash -c "printenv | grep MOODLE > /etc/environment; cron -f"
    volumes:
      - moodledata:/var/www/moodledata
    networks:
      - raisemoodle
    environment:
      MOODLE_DOCKER_DBHOST: postgres
      MOODLE_DOCKER_DBNAME: $POSTGRES_DB
      MOODLE_DOCKER_DBUSER: $POSTGRES_USER
      MOODLE_DOCKER_DBPASS: $POSTGRES_PASSWORD
      MOODLE_DOCKER_DATAROOT: /var/www/moodledata
    depends_on:
      - moodle
  eventsapi:
    build:
      context: services/eventsapi
    networks:
      - raisemoodle
    ports:
      - 8888:80 # Only exposed for developer convenience
    environment:
      - EVENTS_S3_BUCKET
      - EVENTS_S3_PREFIX
  postgres:
    image: "postgres:13"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - raisemoodle
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
networks:
  raisemoodle:
volumes:
  pgdata:
  moodledata:
