version: "3.8"
services:
  moodle:
    build:
      context: .
      dockerfile: moodle/Dockerfile
      target: ${MOODLE_TARGET:-dev}
    volumes: &moodlevolumes
      - moodledata:/var/www/moodledata
      - ./plugins/events:/var/www/html/admin/tool/events
      - ./plugins/study:/var/www/html/mod/study
      - ./plugins/content:/var/www/html/filter/content
      - ./plugins/fe_events_direct:/var/www/html/local/fe_events_direct
      - ./plugins/fe_events_moodle:/var/www/html/local/fe_events_moodle
      - ./plugins/report_raisespikes:/var/www/html/report/raisespikes
      - ./plugins/local_persist:/var/www/html/local/persist
      - .:/repo
    networks:
      - raisemoodle
    environment: &moodleenv
      MOODLE_DOCKER_DBHOST: postgres
      MOODLE_DOCKER_DBNAME: $POSTGRES_DB
      MOODLE_DOCKER_DBUSER: $POSTGRES_USER
      MOODLE_DOCKER_DBPASS: $POSTGRES_PASSWORD
      MOODLE_DOCKER_WWWROOT: http://localhost:8000
      MOODLE_DOCKER_DATAROOT: /var/www/moodledata
      MOODLE_DOCKER_SMTPHOST: mailhog:1025
    ports:
      - 8000:80
    depends_on:
      - postgres
    entrypoint: ["./wait-for-it.sh", "postgres:5432"]
    command: ["--", "docker-php-entrypoint", "apache2-foreground"]

    extra_hosts:
      - "host.docker.internal:host-gateway"
  cron:
    build:
      context: .
      dockerfile: moodle/Dockerfile
    command: /bin/bash -c "printenv | grep MOODLE > /etc/environment; cron -f"
    volumes: *moodlevolumes
    networks:
      - raisemoodle
    environment: *moodleenv
    depends_on:
      - moodle
  contentapi:
    build:
      context: services/contentapi
    volumes:
      - ./services/contentapi/content:/content
    networks:
      - raisemoodle
    ports:
      - 8800:80
  postgres:
    image: "postgres:13"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - raisemoodle
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  pgadmin:
    image: "dpage/pgadmin4"
    networks:
      - raisemoodle
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  mailhog:
    image: mailhog/mailhog
    networks:
      - raisemoodle
    ports:
      - 8025:8025
networks:
  raisemoodle:
volumes:
  pgdata:
  moodledata:
