---
version: "3.8"
services:
  zookeeper:
    image: zookeeper:3.8
    ports:
      - "2181:2181"
    networks:
      - raisemoodle
    profiles:
      - kafka

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1 # This tag is <scala version>-<kafka version>
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      - raisemoodle
    profiles:
      - kafka

  redpanda:
    image: docker.redpanda.com/vectorized/console:master-cb51d72
    environment:
      KAFKA_BROKERS: "kafka:29092"
    ports:
    - 8080:8080
    networks:
      - raisemoodle
    profiles:
      - kafka
