{{- if hasPrefix "https" .Values.moodleWebRoot }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Chart.Name }}-{{ .Values.deploymentName }}-redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
