apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-postgres-creds-{{ .Values.deploymentName }}
type: Opaque
stringData:
  username: {{ .Values.dbUsername }}
  password: {{ .Values.dbPassword }}
