apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: raise-data-daily
spec:
  schedule: "0 21 * * *"
  concurrencyPolicy: "Replace"
  timezone: America/Chicago
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  workflowSpec:
    entrypoint: flow
    templates:
    - name: push-users
      container:
        image: 361171574891.dkr.ecr.us-east-1.amazonaws.com/raise-metrics-analyzer
        command:
          - "bash"
          - "-cxe"
          - |
            aws s3 cp s3://raise-data/algebra1/ay2022/automation/courses.csv courses.csv
            moodle-cli export-bulk courses.csv raise-data algebra1/ay2022/moodle/users users
        env:
          - name: MOODLE_URL
            value: https://raiselearning.org
          - name: MOODLE_TOKEN
            valueFrom:
              secretKeyRef:
                name: raise-data-moodle-creds
                key: token
    - name: push-grades
      container:
        image: 361171574891.dkr.ecr.us-east-1.amazonaws.com/raise-metrics-analyzer
        command:
          - "bash"
          - "-cxe"
          - |
            aws s3 cp s3://raise-data/algebra1/ay2022/automation/courses.csv courses.csv
            moodle-cli export-bulk courses.csv raise-data algebra1/ay2022/moodle/grades grades
        env:
          - name: MOODLE_URL
            value: https://raiselearning.org
          - name: MOODLE_TOKEN
            valueFrom:
              secretKeyRef:
                name: raise-data-moodle-creds
                key: token
    - name: analyze
      container:
        image: 361171574891.dkr.ecr.us-east-1.amazonaws.com/raise-metrics-analyzer
        command:
          - bash
          - -cxe
          - |
            aws s3 cp s3://raise-data/algebra1/ay2022/automation/raise-data-analyzer/results.csv results.csv
            python analyzer.py raise-data algebra1/ay2022/moodle/users results.csv
            aws s3 cp results.csv s3://raise-data/algebra1/ay2022/automation/raise-data-analyzer/results.csv
    - name: flow
      dag:
        tasks:
        - name: push-users
          template: push-users
        - name: push-grades
          template: push-grades
        - name: analyze
          template: analyze
          dependencies:
            - push-users
